export enum DataType {
	UNIQUEIDENTIFIER = 'UNIQUEIDENTIFIER',
	BIGINT = 'BIGINT',
	VARCHAR = 'VARCHAR',
	INT = 'INT',
	TINYINT = 'TINYINT',
	BIT = 'BIT',
	DATE = 'DATE',
	DECIMAL = 'DECIMAL',
	DATETIME = 'DATETIME',
	CHAR = 'CHAR',
	SMALLINT = 'SMALLINT',
	NVARCHAR = 'NVARCHAR'
}
